# Generated by Django 2.2.13 on 2020-06-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferenceService',
            new_name='ReferenceServiceAnalytic',
        ),
    ]
