# Generated by Django 2.2.13 on 2020-06-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0002_auto_20200611_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='record_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='user_from_out',
            field=models.IntegerField(default=0, verbose_name='Dışarıdan gelen kullanıcı sayısı'),
        ),
    ]
