# Generated by Django 2.2.13 on 2020-07-16 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0003_auto_20200617_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceserviceanalytic',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
