# Generated by Django 2.2.13 on 2020-07-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0004_referenceserviceanalytic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceserviceanalytic',
            name='microfilm_mp',
            field=models.IntegerField(default=0, verbose_name='Mikrofilm kullanan vekil sayısı'),
        ),
        migrations.AddField(
            model_name='referenceserviceanalytic',
            name='microfilm_patron_inside',
            field=models.IntegerField(default=0, verbose_name='Mikrofilm kullanan kurum içi personel sayısı'),
        ),
        migrations.AddField(
            model_name='referenceserviceanalytic',
            name='microfilm_patron_outside',
            field=models.IntegerField(default=0, verbose_name='Mikrofim kullanan kurum dışı personel sayısı'),
        ),
        migrations.AddField(
            model_name='referenceserviceanalytic',
            name='microfilm_retired_mp',
            field=models.IntegerField(default=0, verbose_name='Mikrofilm kullanmış emekli vekil sayısı'),
        ),
    ]
