# Generated by Django 2.2.13 on 2020-07-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0007_auto_20200722_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceserviceanalytic',
            name='notes',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Ekstra not alanı.'),
        ),
    ]
