# Generated by Django 2.2.13 on 2020-07-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0008_referenceserviceanalytic_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='notes',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Ekstra not alanı.'),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='online_user_inside',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='online_user_outside',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='open_access_session_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Açık erişim sistemi oturum açmış kullanıcı sayısı.'),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='photocopy_a4_formal',
            field=models.IntegerField(blank=True, default=0, verbose_name='A4 boyutunda resmi fotokopi sayısı.'),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='user_from_inside',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='user_from_out',
            field=models.IntegerField(blank=True, default=0, verbose_name='Dışarıdan gelen kullanıcı sayısı.'),
        ),
    ]
