# Generated by Django 2.2.13 on 2020-07-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0009_auto_20200722_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceserviceanalytic',
            name='photocopy_a3_paid',
            field=models.IntegerField(default=0, verbose_name='A3 boyutunda ücreti ödenmiş fotokopi sayısı.'),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='online_user_inside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='online_user_outside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='open_access_session_count',
            field=models.IntegerField(default=0, verbose_name='Açık erişim sistemi oturum açmış kullanıcı sayısı.'),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='photocopy_a3_formal',
            field=models.IntegerField(default=0, verbose_name='A3 boyutunda resmi fotokopi sayısı.'),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='photocopy_a4_formal',
            field=models.IntegerField(default=0, verbose_name='A4 boyutunda resmi fotokopi sayısı.'),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='user_from_inside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='user_from_out',
            field=models.IntegerField(default=0, verbose_name='Dışarıdan gelen kullanıcı sayısı.'),
        ),
    ]
