# Generated by Django 2.2.13 on 2020-07-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0010_auto_20200722_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceserviceanalytic',
            name='borrowed_books',
        ),
        migrations.RemoveField(
            model_name='referenceserviceanalytic',
            name='photocopy',
        ),
        migrations.RemoveField(
            model_name='referenceserviceanalytic',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='referenceserviceanalytic',
            name='retired_books',
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='date',
            field=models.DateField(verbose_name='Kaydın girildiği tarih'),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='online_user_inside',
            field=models.IntegerField(default=0, verbose_name='İçeriden gelen online kullanıcı sayısı.'),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='online_user_outside',
            field=models.IntegerField(default=0, verbose_name='Dışarıdan gelen online kullanıcı sayısı.'),
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='user_from_inside',
            field=models.IntegerField(default=0, verbose_name='İçeriden gelen kullanıcı sayısı.'),
        ),
    ]
