# Generated by Django 2.2.13 on 2020-07-27 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0011_auto_20200724_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceserviceanalytic',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
