# Generated by Django 2.2.13 on 2020-07-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0012_referenceserviceanalytic_record_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceserviceanalytic',
            name='record_date',
        ),
    ]
