# Generated by Django 2.2.13 on 2020-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0013_remove_referenceserviceanalytic_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceserviceanalytic',
            name='dijitalized_papers',
            field=models.IntegerField(default=0, verbose_name='Dijital kopya sayısı.'),
        ),
    ]
