# Generated by Django 2.2.13 on 2020-08-20 13:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0015_auto_20200729_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(max_length=60, verbose_name='Yayın türü (Kitap, dergi, gazete)')),
            ],
        ),
        migrations.AlterField(
            model_name='referenceserviceanalytic',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Raporun hazırlandığı tarih (Otomatik oluşturulur.)'),
        ),
        migrations.CreateModel(
            name='SaglamaAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_arrived_as_supply', models.IntegerField(default=0, verbose_name='Derlemeden gelen yayın sayısı.')),
                ('pub_arrived_as_gift', models.IntegerField(default=0, verbose_name='Hediye gelen yayın sayısı.')),
                ('pub_bought', models.IntegerField(default=0, verbose_name='Satın alınan yayın sayısı.')),
                ('pub_saved_as_supply', models.IntegerField(default=0, verbose_name='Derlemeden koleksiyona alınan yayın sayısı.')),
                ('pub_saved_as_gift', models.IntegerField(default=0, verbose_name='Hediyelerden koleksiyona alınan yayın sayısı.')),
                ('pub_saved_as_old', models.IntegerField(default=0, verbose_name='Eski etiketiyle koleksiyona alınan yayın sayısı.')),
                ('notes', models.TextField(blank=True, max_length=1500, verbose_name='Ekstra not alanı.')),
                ('reporter_identity', models.CharField(blank=True, max_length=60, verbose_name='Raporu hazırlayan personel adı soyadı.')),
                ('reporter_title', models.CharField(blank=True, max_length=60, verbose_name='Raporu hazırlayan personel ünvanı.')),
                ('report_date', models.DateField(default=django.utils.timezone.now, verbose_name='Raporun hazırlandığı tarih (Otomatik oluşturulur.)')),
                ('date', models.DateField(verbose_name='Raporun ait olduğu tarih')),
                ('pub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cockpit.PubType')),
            ],
        ),
    ]
