# Generated by Django 2.2.13 on 2020-08-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0016_auto_20200820_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaglamaReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_identity', models.CharField(blank=True, max_length=60, verbose_name='Raporu hazırlayan personel adı soyadı.')),
                ('reporter_title', models.CharField(blank=True, max_length=60, verbose_name='Raporu hazırlayan personel ünvanı.')),
                ('date', models.DateField(verbose_name='Raporun ait olduğu tarih')),
            ],
        ),
        migrations.RemoveField(
            model_name='saglamaanalytic',
            name='reporter_identity',
        ),
        migrations.RemoveField(
            model_name='saglamaanalytic',
            name='reporter_title',
        ),
        migrations.AlterField(
            model_name='saglamaanalytic',
            name='pub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cockpit.PubType', verbose_name='Yayın türü (Kitap, dergi, gazete)'),
        ),
        migrations.AddField(
            model_name='saglamaanalytic',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cockpit.SaglamaReport', verbose_name='Sağlama raporu:'),
            preserve_default=False,
        ),
    ]
