# Generated by Django 2.2.13 on 2020-08-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0017_auto_20200820_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saglamaanalytic',
            name='report',
        ),
    ]
