# Generated by Django 2.2.13 on 2020-08-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0018_remove_saglamaanalytic_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='saglamaanalytic',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cockpit.SaglamaReport', verbose_name='Sağlama raporu:'),
            preserve_default=False,
        ),
    ]
