# Generated by Django 2.2.13 on 2020-08-26 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0019_saglamaanalytic_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_arrived_as_supply', models.IntegerField(default=0, verbose_name='Derlemeden gelen yayın sayısı.')),
                ('pub_arrived_as_gift', models.IntegerField(default=0, verbose_name='Hediye gelen yayın sayısı.')),
                ('pub_bought', models.IntegerField(default=0, verbose_name='Satın alınan yayın sayısı.')),
                ('pub_saved_as_supply', models.IntegerField(default=0, verbose_name='Derlemeden koleksiyona alınan yayın sayısı.')),
                ('pub_saved_as_gift', models.IntegerField(default=0, verbose_name='Hediyelerden koleksiyona alınan yayın sayısı.')),
                ('pub_saved_as_old', models.IntegerField(default=0, verbose_name='Eski etiketiyle koleksiyona alınan yayın sayısı.')),
                ('notes', models.TextField(blank=True, max_length=1500, verbose_name='Ekstra not alanı.')),
                ('report_date', models.DateField(default=django.utils.timezone.now, verbose_name='Raporun hazırlandığı tarih (Otomatik oluşturulur.)')),
                ('date', models.DateField(verbose_name='Raporun ait olduğu tarih')),
                ('pub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cockpit.PubType', verbose_name='Yayın türü (Kitap, dergi, gazete)')),
            ],
        ),
        migrations.CreateModel(
            name='AcquisitionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_identity', models.CharField(blank=True, max_length=60, verbose_name='Raporu hazırlayan personel adı soyadı.')),
                ('reporter_title', models.CharField(blank=True, max_length=60, verbose_name='Raporu hazırlayan personel ünvanı.')),
                ('posted_book', models.IntegerField(default=0, verbose_name='Kütüphaneden gönderilen kitap saıyısı.')),
                ('refactored_items', models.IntegerField(default=0, verbose_name='Yeniden düzenlenip envanteri yapılan yayın sayısı.')),
                ('date', models.DateField(verbose_name='Raporun ait olduğu tarih')),
            ],
        ),
        migrations.DeleteModel(
            name='SaglamaAnalytic',
        ),
        migrations.AddField(
            model_name='acquisitionanalytic',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cockpit.AcquisitionReport', verbose_name='Sağlama raporu:'),
        ),
    ]
