# Generated by Django 2.2.13 on 2020-08-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0020_auto_20200826_0821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaglamaReport',
        ),
    ]
