# Generated by Django 2.2.13 on 2020-08-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0021_delete_saglamareport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisitionanalytic',
            name='date',
        ),
        migrations.RemoveField(
            model_name='acquisitionanalytic',
            name='notes',
        ),
        migrations.AddField(
            model_name='acquisitionreport',
            name='notes',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Ekstra not alanı.'),
        ),
    ]
