# Generated by Django 2.2.13 on 2020-08-28 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0022_auto_20200826_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisitionanalytic',
            name='report_date',
        ),
        migrations.AddField(
            model_name='acquisitionreport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 11, 24, 2, 739549, tzinfo=utc), verbose_name='Kayıdın oluşturulduğu tarih.'),
        ),
    ]
