# Generated by Django 2.2.13 on 2020-08-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0026_auto_20200828_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisitionreport',
            name='created_at',
        ),
    ]
