# Generated by Django 2.2.13 on 2020-08-28 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0027_remove_acquisitionreport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitionreport',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Raporun hazırlandığı tarih (Otomatik oluşturulur.)'),
        ),
    ]
