# Generated by Django 2.2.13 on 2020-10-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0028_acquisitionreport_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisitionanalytic',
            name='pub_type',
        ),
    ]
