# Generated by Django 2.2.13 on 2020-10-12 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit', '0029_remove_acquisitionanalytic_pub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitionanalytic',
            name='pub_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cockpit.PubType', verbose_name='Yayın türü (Kitap, dergi, gazete)'),
            preserve_default=False,
        ),
    ]
